description "Termucash Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env TERMUCASHD_BIN="/usr/bin/termucashd"
env TERMUCASHD_USER="termucash"
env TERMUCASHD_GROUP="termucash"
env TERMUCASHD_PIDDIR="/var/run/termucashd"
# upstart can't handle variables constructed with other variables
env TERMUCASHD_PIDFILE="/var/run/termucashd/termucashd.pid"
env TERMUCASHD_CONFIGFILE="/etc/termucash/termucash.conf"
env TERMUCASHD_DATADIR="/var/lib/termucashd"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # termucashd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$TERMUCASHD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run termucashd."
        echo "The setting must appear in $TERMUCASHD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Termucash Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$TERMUCASHD_PIDDIR"
    chmod 0755 "$TERMUCASHD_PIDDIR"
    chown $TERMUCASHD_USER:$TERMUCASHD_GROUP "$TERMUCASHD_PIDDIR"
    chown $TERMUCASHD_USER:$TERMUCASHD_GROUP "$TERMUCASHD_CONFIGFILE"
    chmod 0660 "$TERMUCASHD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$TERMUCASHD_PIDFILE" \
    --chuid $TERMUCASHD_USER:$TERMUCASHD_GROUP \
    --exec "$TERMUCASHD_BIN" \
    -- \
    -pid="$TERMUCASHD_PIDFILE" \
    -conf="$TERMUCASHD_CONFIGFILE" \
    -datadir="$TERMUCASHD_DATADIR" \
    -disablewallet \
    -daemon

