#!/bin/bash
#
#  termucashd The termucash core server.
#
#
# chkconfig: 345 80 20
# description: termucashd
# processname: termucashd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/termucashd, see below
if [ -f /etc/sysconfig/termucashd ]; then
        . /etc/sysconfig/termucashd
fi

RETVAL=0

prog=termucashd
# you can override the lockfile via TERMUCASHD_LOCKFILE in /etc/sysconfig/termucashd
lockfile=${TERMUCASHD_LOCKFILE-/var/lock/subsys/termucashd}

# termucashd defaults to /usr/bin/termucashd, override with TERMUCASHD_BIN
termucashd=${TERMUCASHD_BIN-/usr/bin/termucashd}

# termucashd opts default to -disablewallet, override with TERMUCASHD_OPTS
termucashd_opts=${TERMUCASHD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $termucashd $termucashd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
